linters-settings:
  depguard:
    rules:
      prevent_unmaintained_packages:
        list-mode: lax # allow unless explicitely denied
        files:
          - $all
          - "!$test"
        allow:
          - $gostd
        deny:
          - pkg: io/ioutil
            desc: "replaced by io and os packages since Go 1.16: https://tip.golang.org/doc/go1.16#ioutil"
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0.8
  gocyclo:
    min-complexity: 10
    max-complexity: 12
  maligned:
    suggest-new: true
  dupl:
    threshold: 500
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: github.com/reportportal/service-index
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc
      - commentFormatting
      - yodaStyleExpr
      - unnamedResult
      - commentedOutCode
      - assignOp
      - docStub

linters:
  enable-all: true
  disable:
    - prealloc
    - gochecknoglobals
    - gocyclo
    - gocritic
    - interfacer
    - wsl
    - funlen
    - unused
    - gomnd
    - godot
    - exhaustivestruct
    - exhaustruct
    - varnamelen
    - gci
    - nosnakecase
    - ifshort
    - scopelint
    - depguard
run:
  # default concurrency is a available CPU number
  concurrency: 1
#  skip-dirs:
#    - test/testdata_etc

issues:
  exclude-rules:
    - text: "weak cryptographic primitive"
      linters:
        - gosec