language: go

go:
  - 1.12.9

env:
  - GO111MODULE=on

before_script:
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint

script: make checkstyle build

notifications:
  slack: reportportal-dev:fl6xWHVQp1jvsMmCJxYW9YKP

after_success:
  - npm install -g codecov
  - codecov
