language: go

go:
  - 1.14.x

env:
  - GO111MODULE=on

before_install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.28.0

script: make checkstyle build

notifications:
  slack: reportportal-dev:fl6xWHVQp1jvsMmCJxYW9YKP

after_success:
  - npm install -g codecov
  - codecov
